/**
 * Definition for singly-linked list.
 * struct ListNode {
 *     int val;
 *     ListNode *next;
 *     ListNode() : val(0), next(nullptr) {}
 *     ListNode(int x) : val(x), next(nullptr) {}
 *     ListNode(int x, ListNode *next) : val(x), next(next) {}
 * };
 */
class Solution {
public:
    bool isPalindrome(ListNode* head) {
        vector<int> ans;
        ListNode *temp = head;
        while(temp){
            ans.push_back(temp->val);
            temp = temp->next;
        }
        int i = 0, j = ans.size()-1;
        while(i<j){
            if(ans[i] == ans[j]){
                i++;
                j--;
            } else{
                return false;
            }
        }
        return true;
    }
};
